# Generated by Django 4.2.7 on 2025-10-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_rename_cantidad_producto_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
